all:
	(cd Blocked; make all)
	(cd BlockedMulti; make all)
	(cd Normal; make all)
	(cd Transposed; make all)
	
clean:
	(cd Blocked; make clean)
	(cd BlockedMulti; make clean)
	(cd Normal; make clean)
	(cd Transposed; make clean)